### ISSUE TITLE
Are plugins working in k9salpha?

### ISSUE THREAD

**Issue by SteveF4** [imhotepio/k9salpha#1]
I can't seem to get k9salpha to recognise plugins. I noticed [the plugins file is now `$HOME/.config/k9s-alpha/plugins.yaml`](https://k9salpha.io/topics/configs/plugins/) instead of [the old k9s location `$HOME/.k9s/plugin.yml`](https://k9scli.io/topics/plugins/). After copying my `$HOME/.k9s/plugin.yml` file to `$HOME/.config/k9s-alpha/plugins.yaml` and restarting k9salpha, the plugin does not seem to work. I checked the [output of the tree command in the demo video (at time 3:40)](https://www.youtube.com/watch?v=hLYK0oPLOIY), and that confirmed what the documentation says about the new file location. So the documentation is correct. I just can't get any plugins to work. I tried several user contributed plugins, but the one I'd really like to get working is [here](https://github.com/derailed/k9s/issues/832).

**Describe the bug**
When I copied a working plugin.yml file from k9s to `$HOME/.config/k9s-alpha/plugins.yaml`, the plugin shortcut does not show up in the help menu, and nothing happens when I hit the configured hotkey in k9salpha. I got the plugin to work under k9s, but the same plugin configuration does not seem to work in k9salpha.

**To Reproduce**
1. Install xdotool (Linux).
2. Create file `$HOME/.config/k9s-alpha/plugins.yaml` with the following content:
```
plugin:
  go-back:
    shortCut: q
    description: "Go Back"
    scopes:
    - all
    command: xdotool
    background: true
    confirm: false
    args:
    - key
    - Escape
```
3. Start `k9salpha`
4. Hit `?` on the keyboard: the shortcut key from the plugin (`q`) is not shown.
5. Run `:pods` and press enter on the highlighted pod. The menu at the bottom says `<pod><containers>`
6. Press the shortcut defined in the plugin file: `q` and nothing happens. The menu at the bottom still says `<pod><containers>` instead of the expected  `<pod>`. 

**Expected behavior**
I was expecting to see the plugin execute. In k9s, there was an orange message that flashed at the bottom of the screen to say the command was run successfully. In k9salpha, there is no orange message to say that the command was run.

**Screenshots**
There are no screenshots as k9salpha is not doing what I was hoping it would.

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04 LTS x64 XFCE, X11
 - K9s: v1.0.0-rc.1    
 - K8s: v1.18.3+cdb0358

**Additional context**
I'm new to plugins, so there may be a detail that I've missed or overlooked. I tried to get more information by running `k9salpha --logLevel debug` but that did not seem to produce extra output, and there was no a log file generated.

**Comment by derailed** [comment]
@SteveF4 - Thank you for posting issue #1! Please take a look at the [plugins doc page](https://k9salpha.io/topics/configs/plugins) and try to run the sample to make sure all is cool. At first glance 'plugin' in the yaml should be plural and your custom mnemonic should show on the top menu if the plugins are indeed picked up. 
Also try `k9salpha info` for logs location.

**Comment by SteveF4** [comment]
Thank-you @derailed! You called it. I just needed to change `plugin` to `plugins` inside my plugins.yaml file. Once that was fixed, everything was great. Thanks for the tip about `k9salpha info` too. I will surely use that lots over the coming years as I change my configuration.

**Comment by derailed** [comment]
@SteveF4 - Thank you Steve! No problem just happy to hear you're back up and running!
