### ISSUE TITLE
Skins documentation contains references to ".yml" files, should be ".yaml"

### ISSUE THREAD

**Issue by SteveF4** [imhotepio/k9salpha#4]
<img src="https://raw.githubusercontent.com/imhotepio/k9salpha/master/assets/k9s_err.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
In the k9salpha documentation at https://k9salpha.io/topics/configs/skins/, the documentation references:
- $XDG_CONFIG_HOME/.k9s-alpha/default-skins.yml
- $XDG_CONFIG_HOME/.k9s-alpha/contexts/contextXXX/skins.yml
- $XDG_CONFIG_HOME/.k9s-alpha/contexts/fred/skins.yml
- In the example skin file, comment on the first line: # $XDG_CONFIG_HOME/contexts/fred/skins.yml 

I found that $XDG_CONFIG_HOME/.k9s-alpha/default-skins.yml was not applied when I ran k9salpha. If I change the extension to .yaml ($XDG_CONFIG_HOME/.k9s-alpha/default-skins.*yaml*) the skin configuration is picked up. This appears to be a copy-paste issue from the k9s project documentation?

**To Reproduce**
1. Configure a skin in $XDG_CONFIG_HOME/.k9s-alpha/default-skins.yml
2. Reload k9salpha. Your changes are not detected.
3. Rename $XDG_CONFIG_HOME/.k9s-alpha/default-skins.yml to $XDG_CONFIG_HOME/.k9s-alpha/default-skins.yaml
4. Reload k9salpha. The configuration is applied.

**Expected behavior**
The documentation references to ".yml" should probably be changed to ".yaml".

**Screenshots**
![image](https://user-images.githubusercontent.com/50889087/116626023-7780f900-a8ff-11eb-932f-6f754256ac27.png)

**Versions (please complete the following information):**
 - OS: Linux Lite (Ubuntu 20.04 LTS) x64
 - K9s: v1.0.0-rc.1
 - K8s: v1.19.0+a5a0987

**Additional context**
None.

**Comment by derailed** [comment]
@SteveF4 Great catch! Thank you Steve!
