### ISSUE TITLE
Question: option to hide K9salpha logo?

### ISSUE THREAD

**Issue by SteveF4** [imhotepio/k9salpha#5]
Hi Fernand,

I do like ASCII art, but find that the K9salpha logo can obscure the menu options at the top of the screen, especially on small laptop screens, or desktops with larger scaling. Is there a way a way to turn the logo off? If not, I would like to submit it as a feature request for consideration in a future version of K9salpha. Perhaps a toggle, hidden away in config.yaml.

Here is a screenshot of a typical window from my desktop, illustrating how the menu is hidden by the logo:

![image](https://user-images.githubusercontent.com/50889087/116630864-e747b180-a908-11eb-9561-99d5e0d98937.png)

It's not a big deal, but it would save some time opening the help or adjusting the window size. I just love K9salpha. It makes working with Kubernetes and OpenShift fun and easy. Thank-you for all the work you've done,

Steve.

**Comment by derailed** [comment]
Thank you for your kind words @SteveF4!! Yes we can add that in. In the mean time you can leverage `Ctrl-e` which acts as a toggle on the header and you can leverage '?' to fish out the commands. The clusterinfo will be summarized in that mode. Additionally, you can also set the config file option `headless: true` to remember this setting. For my workflow, 'home to a thousand window's the logo helps me quickly locate my Alpha sessions ;) That said we can add easily add an option to axe out the logo if folks feel that is a feature worth having...

**Comment by SteveF4** [comment]
Oh, thanks @derailed! That `Ctrl-e` setting is pretty useful. Never noticed it before. I'll just use that and the `?` key, and will make a point to try the other options under help to discover what else I'm missing. Thanks again.
