### ISSUE TITLE
k8s resources not shown in k9salpha v1.0.0-rc2

### ISSUE THREAD

**Issue by mprimeaux** [imhotepio/k9salpha#8]
<img src="https://raw.githubusercontent.com/imhotepio/k9salpha/master/assets/k9s_err.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
No k8s resources are shown in k9salpha v1.0.0-rc2 on Apple Silicon (arm64) but do show in k9s.

```shell
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
```

**To Reproduce**
1. Start minikube 
2. Start k9salpha
3. Go to Pulses (`:pu`)

**Expected behavior**
I expect to see Pods, Deployments, ReplicaSets, StatefulSets, etc

**Screenshots**

**Here is what I see in k9salpha:**

![k9salpha - Pulses](https://user-images.githubusercontent.com/293512/170761792-66e6cee1-8f8f-45a8-93c8-77c0258e144d.png)
![k9salpha - Pods](https://user-images.githubusercontent.com/293512/170761840-7158d099-b215-45e6-b971-49f29408fd96.png)

**Here is what I see in k9s:**

![SS-2](https://user-images.githubusercontent.com/293512/170761978-1827cb16-1d07-40dc-80c0-d3f2c6d1cfe3.png)

**Versions (please complete the following information):**
 - OS: macOS Monterrey 12.4
 - K9salpha: v1.0.0-rc2 
 - K8s: 1.22.9
 - Host Machine: Mac Studio (Apple M1 Ultra, 128 GB RAM)

**Additional context**

None at this time.

**Comment by mprimeaux** [comment]
I think we can close this as I received an email from k9salpha support, which reads:

> As for the pulses view by default it will use you current namespace which appear to be default. To look at pulses in a the `fred` namespace you can use `:pulses fred`

After starting k9salpha, I issued the `:pu kube-system` command and I do see the expected Kubernetes objects.  Since the default namespace is "default", going to `:namespaces` and selecting `all` works as expected. 

I should have used `--help` :)

```shell
❯ k9salpha --help                                                                                                                                          ─╯
K9s is a CLI to view and manage your Kubernetes clusters.

Usage:
  K9sAlpha [flags]
  K9sAlpha [command]

Available Commands:
  help        Help about any command
  info        Print configuration info
  version     Print version/build info

Flags:
  -A, --all-namespaces                 Launch K9s in all namespaces
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
  -c, --command string                 Overrides the default resource to load when the application launches
      --context string                 The name of the kubeconfig context to use
      --crumbsless                     Turn K9s crumbs off
      --headless                       Turn K9s header off
  -h, --help                           help for K9sAlpha
      --insecure-skip-tls-verify       If true, the server's caCertFile will not be checked for validity
      --kubeconfig string              Path to the kubeconfig file to use for CLI requests
  -l, --logLevel string                Specify a log level (info, warn, debug, error, fatal, panic, trace) (default "info")
  -n, --namespace string               If present, the namespace scope for this CLI request
      --readonly                       Sets readOnly mode by overriding readOnly configuration setting
  -r, --refresh int                    Specify the default refresh rate as an integer (sec) (default 2)
      --request-timeout string         The length of time to wait before giving up on a single server request
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use
      --write                          Sets write mode by overriding the readOnly configuration setting

Use "K9sAlpha [command] --help" for more information about a command.
```

Thanks for your help!

**Comment by derailed** [comment]
@mprimeaux Excellent! Thank you...
